### ISSUE TITLE
looking for a new maintainer

### ISSUE THREAD

**Issue by mackuba** [mackuba/jslint_on_rails#16]
Last year I decided to leave the webdev world and concentrate only on Cocoa development. I still love Ruby as a language (especially as compared to ObjC - Swift is much better though), but it was just too much effort to try to keep up with Ruby, JS and Cocoa all the time, and I had to choose something.

I haven't been up to date with all the latest developments in the Ruby world since then, I'm not even sure which version of Ruby is the latest stable one now (2.1 I think?). And obviously I had no use for a Rails JSLint plugin for some time now. I'm not willing to put any more effort into this gem, since I have other projects to maintain too, but if someone is interested in taking it over and maintaining it, I can transfer the ownership of the repo and the RubyGems entry.

**Current project status:**

It hasn't been updated in a loooong time. The bundled JSLint version hasn't been updated for even longer, ever since Crockford made some major changes there and added some annoying checks which couldn't be disabled (I think he might have changed that back later). If you want to update it, you'd need to either copy my hacks (those 3 extra options) over to the newest JSLint, or just drop these options (I don't really care).

There's some code on `master` which hasn't been released that gets rid of Rhino and lets you use any execjs-compatible JS runtime. It should work, or at least it did, though you'd have to test it (is execjs still a thing?). There's also some refactoring done on the `hackkrk` branch and unmerged, and some experiments with output coloring in the last commits on `master`. You can use those if you want.

**Regarding JSHint:**

I don't think it makes sense to drop JSLint and switch to JSHint, there are already a few forks that have done just that and re-released the gem as `jshint_on_rails`. And I don't think it makes sense to try to support both in one gem, as they have significantly diverged in the last few years and the options lists would have to be completely different - but you could try to do that if you want (there are some old commits made in that direction on the `jshint` branch).

cc @hlascelles @khansen @wok @wyattearp

**Comment by wyattearp** [comment]
@jsuder this has been buried in my forums mail and I'm just digging out. Did you manage to find a maintainer? If not, let me know.

**Comment by mackuba** [comment]
Nope, I haven't.
