### ISSUE TITLE
Ubuntu install

### ISSUE THREAD

**Issue by drewwells** [mackuba/jslint_on_rails#2]
I tried installing this via gem deployed with apt on Ubuntu.  I installed via your instructions:
gem install jslint_on_rails

It fails with:
no such file to load -- jslint/tasks

**Comment by mackuba** [comment]
A few questions:
- which jslint_on_rails version you've installed? latest (1.0.4)?
- what is your app based on? Rails 2, Rails 3, something else?
- how do you include the gem in your app? with Bundler (Gemfile), with manual require? Did you add anything to the Rakefile?

**Comment by drewwells** [comment]
jslint_on_rails version: 1.0.4
Rails 1.8 installed via apt
I installed jslint_on_rails with gem via apt, as described here https://help.ubuntu.com/community/RubyOnRails#RubyGems via apt
I tried installing another gem 'update_system' it created a bin directory with the gem binary inside it.  jslint_on_rails did not create a file in this directory

I included it in a Rakefile as require 'jslint/tasks' (not sure what you mean by Bundler)

**Comment by mackuba** [comment]
I think you mean Ruby 1.8, not Rails 1.8, right? I don't think there has ever been a 1.8 version of Rails, and even if it was, it would be a really old version...

**Comment by drewwells** [comment]
Rails 2, Ruby 1.8.  I didn't have rails installed, I installed it still getting the same error.

~/gen4-webapps-client/iifviewer/rakefile.rb:2:in `require'
~/gen4-webapps-client/iifviewer/rakefile.rb:2
/usr/lib/ruby/1.8/rake.rb:2383:in`load'
/usr/lib/ruby/1.8/rake.rb:2383:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2017:in`load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2016:in`load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28

**Comment by mackuba** [comment]
What's in your rakefile?

**Comment by drewwells** [comment]
I've made a new one, here's the contents:
require 'jslint/tasks'

**Comment by mackuba** [comment]
Honestly, I don't really understand what you're trying to achieve here... This gem is supposed to test Javascripts in your Rails webapp (though it should work with other similar frameworks too). If you had a Rails webapp, you'd have an auto-generated Rakefile (not to mention you'd have some Javascripts to test), but you don't seem to have one. So what exactly are you trying to test?...

**Comment by drewwells** [comment]
I have JavaScript files, I'm showing that the require is failing.  I don't get far enough to test the JavaScript files.  I'm asking if you know anything about how these gems are called because it can not find the required libraries.

**Comment by mackuba** [comment]
Do you have a Rails web app or a web app using any other Ruby framework, or do you have just the Javascript files and nothing else?

**Comment by drewwells** [comment]
No, I'm using rake as a build file for a plain PHP project.  I'm not using Rails in any way.  I was hoping to use your plugin as a shortcut to managing rhino/jslint.js myself.

**Comment by mackuba** [comment]
Ah, now we're talking. My readme doesn't really describe your case...

I think such rakefile will do for you (and you don't need the rails gem at all):

```
require 'yaml'
require 'jslint'
require 'jslint/tasks'
JSLint.config_path = "config/jslint.yml"
```

The first line shouldn't really be necessary, but I didn't foresee such a case and my gem doesn't load the gem which it later uses (yaml), it assumes it's loaded, and in your case it won't be, so you need to load it manually. The second line is more or less what I meant by "install the gem in your application using whatever technique is recommended for your framework". In the last line, choose whatever works for you, depending on what your app's directory structure is.

Then call `rake jslint:copy_config` once to create a sample config, and edit it to suit your needs (the default template looks for scripts in subdirectories of ./public/javascripts), and then `rake jslint` should test your scripts.

As for Bundler, it's an awesome tool for managing gem depenencies in Ruby apps, check out http://gembundler.com/ if you're interested.
