### ISSUE TITLE
predef comma-separated string doesn't work

### ISSUE THREAD

**Issue by sarahmei** [mackuba/jslint_on_rails#3]
In jslint.yml, I have this:

```
predef:   'window,$,jQuery' # Names of predefined global variables - comma-separated string
```

This passes the string on the command like, like so:

```
java -cp /full/path/to/rhino.jar org.mozilla.javascript.tools.shell.Main /full/path/to/jslint.js [other options],predef="window,$,jQuery",[more other options]
```

However, the rhino function at the end of lint.js splits on commas to separate options, which means this isn't parsed correctly. The only way I've found to make it work is to put the following (slightly ridiculous) string in jslint.yml:

```
predef:   'new Array("window").concat(["$"]).concat(["jQuery"])'
```

**Comment by sarahmei** [comment]
There is also a fork that passes options as json to get around this problem: https://github.com/svenw/jslint_on_rails

**Comment by mackuba** [comment]
I've changed the code to separate options with & instead of commas - since predef is the only string option and & isn't a valid character for variable names, this shouldn't break anything else. Try the version from master, it should work now.

**Comment by sarahmei** [comment]
Thanks, I will give it a try.

**Comment by mackuba** [comment]
So, is it working?

**Comment by outaTiME** [comment]
variables like $, $LAB, $D non work =(

**Comment by mackuba** [comment]
Actually, $ does work, it doesn't work if there's anything else after the $ because Bash interprets it as a variable... Thanks for info, I've pushed version 1.0.6 with a fix for this (also, you can define predef as an array if the line is too long).

**Comment by outaTiME** [comment]
Excelent men, now rocks !!
